name: brew bump
on:
  workflow_dispatch:
  pull_request:
  schedule:
    # every day at 6am
    - cron: "0 6 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  get-outdated-formulae-and-casks:
    name: Get outdated formulae and casks
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setmatrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Output matrix
        run: |
          OUTDATED=$(brew livecheck --json --tap fdkevin0/tap | jq -c '[.[] | select(.version.outdated == true) | . + {type: (if .cask then "cask" else "formula" end), name: (.cask // .formula)}]')
          echo $OUTDATED
          echo matrix="$OUTDATED" >> $GITHUB_OUTPUT
        id: setmatrix

  bump-versions:
    needs: get-outdated-formulae-and-casks
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.get-outdated-formulae-and-casks.outputs.matrix) }}
    name: Bump ${{ matrix.name }} to ${{ matrix.version.latest }}
    runs-on: macos-13
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-
      - name: tap repo and set token
        run: |
          brew tap fdkevin0/tap
          cd $(brew tap-info --json fdkevin0/tap | jq -r '.[].path')
          git remote set-url origin 'https://x-access-token:${{ github.token }}@github.com/fdkevin0/homebrew-tap'
      - name: Set up git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: brew bump ${{ matrix.type }} ${{ matrix.name }} and open PR
        run: |
          brew bump-${{ matrix.type }}-pr fdkevin0/tap/${{ matrix.name }} --version=${{ matrix.version.latest }} --no-browse --no-fork
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}